CREATE TABLE IF NOT EXISTS task (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR NOT NULL,
    description TEXT,
    user_id BIGINT,
    CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users (id)
);