name: Build and Test with Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write

    steps:
      - name: Checkout main project
        uses: actions/checkout@v3

      - name: Checkout starter_t1
        uses: actions/checkout@v3
        with:
          repository: W4NTER/starter_t1
          path: starter_t1

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install starter to local Maven repo
        run: mvn install -f starter_t1/pom.xml

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Upload JaCoCo coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: 📊 Code Coverage Report
          update-comment: true
