name: Build and Test with Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout main project
        uses: actions/checkout@v3

      - name: Checkout starter_t1
        uses: actions/checkout@v3
        with:
          repository: W4NTER/starter_t1
          path: starter_t1

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install starter to local Maven repo
        run: mvn install -f starter_t1/pom.xml

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Check if jacoco.xml exists
        run: |
          if [ -f target/site/jacoco/jacoco.xml ]; then
            echo "jacoco.xml found"
          else
            echo "jacoco.xml not found"
            exit 1
          fi

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Compile and run the Java script to update README badge
        run: |
          javac scripts/UpdateCoverageBadge.java
          java -cp . scripts.UpdateCoverageBadge

# Довольно плохой способ закинуть покрытие тестов в README, но разок реализовать можно)
      - name: Commit updated README.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          CURRENT_BRANCH=${GITHUB_HEAD_REF}
          git fetch origin $CURRENT_BRANCH
          git checkout $CURRENT_BRANCH
          
          git diff --quiet README.md || echo "README.md has changes"
          
          if git diff --quiet README.md; then
            echo "No changes to README.md, skipping commit."
          else
            git add README.md
            git commit -m "Update coverage badge"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:$CURRENT_BRANCH
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JaCoCo coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: 📊 Code Coverage Report
          update-comment: true
